//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientZnakiZodiaka.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassHoroskop", Namespace="http://schemas.datacontract.org/2004/07/ZnakiLibrary")]
    [System.SerializableAttribute()]
    public partial class ClassHoroskop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discription {
            get {
                return this.DiscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscriptionField, value) != true)) {
                    this.DiscriptionField = value;
                    this.RaisePropertyChanged("Discription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHoroscop")]
    public interface IHoroscop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoroscop/ConnectionDataBase", ReplyAction="http://tempuri.org/IHoroscop/ConnectionDataBaseResponse")]
        ClientZnakiZodiaka.ServiceReference1.ClassHoroskop ConnectionDataBase(int day, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoroscop/ConnectionDataBase", ReplyAction="http://tempuri.org/IHoroscop/ConnectionDataBaseResponse")]
        System.Threading.Tasks.Task<ClientZnakiZodiaka.ServiceReference1.ClassHoroskop> ConnectionDataBaseAsync(int day, int month);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHoroscopChannel : ClientZnakiZodiaka.ServiceReference1.IHoroscop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoroscopClient : System.ServiceModel.ClientBase<ClientZnakiZodiaka.ServiceReference1.IHoroscop>, ClientZnakiZodiaka.ServiceReference1.IHoroscop {
        
        public HoroscopClient() {
        }
        
        public HoroscopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoroscopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoroscopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoroscopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientZnakiZodiaka.ServiceReference1.ClassHoroskop ConnectionDataBase(int day, int month) {
            return base.Channel.ConnectionDataBase(day, month);
        }
        
        public System.Threading.Tasks.Task<ClientZnakiZodiaka.ServiceReference1.ClassHoroskop> ConnectionDataBaseAsync(int day, int month) {
            return base.Channel.ConnectionDataBaseAsync(day, month);
        }
    }
}
